# Database Settings
spring.datasource.url=jdbc:mysql://${DBHOST}:${DBPORT}/${DBDATABASE}?rewriteBatchedStatements=true
spring.datasource.username=${DBUSER}
spring.datasource.password=${DBPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

cpu.core=8
spring.datasource.hikari.maximum-pool-size=16
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

## Security Settings
# CSRF Settings
csrf.cookie-domain=chessopeningstat.com
csrf.cookie-sameSite=Strict
csrf.cookie-secure=true
# CORS Settings
cors.allowed-origins=https://www.chessopeningstat.com
