# Database Settings
spring.datasource.url=jdbc:h2:file:../database/testdb;MODE=MySQL;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

cpu.core=12
spring.datasource.hikari.maximum-pool-size=24
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

## Security Settings
# CSRF Settings
csrf.cookie-domain=localhost
csrf.cookie-sameSite=Lax
csrf.cookie-secure=false
# CORS Settings
cors.allowed-origins=http://localhost:3001

