spring.application.name=backend

# Active profile
spring.profiles.active=prod

# External API Settings
api.lichess.base-url=https://lichess.org
api.chesscom.base-url=https://api.chess.com

# Logging settings
logging.level.com.chessopeningstats=DEBUG

spring.data.redis.host=${REDISHOST}
spring.data.redis.port=${REDISPORT}
spring.data.redis.username=${REDISUSER}
spring.data.redis.password=${REDISPASSWORD}